## DO NOT run during play. Editor-time only — bakes premade island terrain to .tres resources.
@tool
extends EditorScript


func _run() -> void:
	_bake_one(&"island_meadows_01", 160, 10.0)
	_bake_one(&"island_forest_01",  160, 10.0)
	_bake_one(&"island_tundra_01",  160, 10.0)
	_bake_one(&"island_desert_01",  160, 10.0)
	# Mainland is currently runtime-generated by mainland_terrain.gd. Bake here too so the
	# scene can be swapped to baked .tres references later for faster cold start.
	_bake_one(&"island_mainland_01", 800, 40.0)


func _bake_one(def_id: StringName, size_m: int, max_height_m: float) -> void:
	var seed_ := hash(String(def_id))
	var data := IslandGenerator.generate(seed_, size_m, max_height_m)
	var out_dir := "res://assets/islands/"
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(out_dir))
	var mesh_path  := "%s%s_mesh.tres"       % [out_dir, def_id]
	var col_path   := "%s%s_collider.tres"   % [out_dir, def_id]
	var wall_path  := "%s%s_shore_wall.tres" % [out_dir, def_id]
	ResourceSaver.save(data["mesh"], mesh_path)
	ResourceSaver.save(data["collider"], col_path)
	ResourceSaver.save(data["shore_wall"], wall_path)
	print("baked ", def_id)
